### ISSUE TITLE
2.3 Random Forest Listing 2.4

### ISSUE THREAD

**Issue by JPL-JUNO** [gkunapuli/ensemble-methods-notebooks#1]
Cell 2, Line 16, when calculate the accuracy of test set, I think should use `rf_ens[j]` to calculate instead of `bag_ens[j]` and there is not need to keep `bag` , `X_bag`, `y_bag`. `scikit-learn` doesn't provide `estimators_samples_` for `random forest`

**Comment by gkunapuli** [comment]
Thanks for the catch. I'll push this in along with some other changes soon.

**Comment by gkunapuli** [comment]
Code has been pushed. Closing issue.
